### ISSUE TITLE
Move the USE CASES from item 3.1 - "User Interfaces" to the correct place in SRS, pls.; See The comment below.

### ISSUE THREAD

**Issue by eljunia** [TeamEarth/BankAccountingSystem#10]
According to the today's meeting, all the use cases from p. 3.1 - "User Interfaces" should be moved to the main features in SRS; I made some changes: fail instead of trial and so on; the paragraphs about which I am not sure if they should be deleted, are in red colour. Please, make the changes to your own discretion.

**Comment by VasilJivkov** [comment]
Pulled the uses cases out of the SRS, and placed them in a separate file in the main directory
